ALTER TABLE departments
DISABLE CONSTRAINT DEPT_ID_PK;

ALTER TABLE departments
DISABLE CONSTRAINT DEPT_MGR_FK;

ALTER TABLE departments
DISABLE CONSTRAINT DEPT_LOC_FK;
-------------------------------------------------
ALTER TABLE employees
DISABLE CONSTRAINT EMP_DEPT_FK;

ALTER TABLE employees
DISABLE CONSTRAINT EMP_JOB_FK;

ALTER TABLE employees
DISABLE CONSTRAINT EMP_MANAGER_FK;