-- ALTER TABLE departments ENABLE CONSTRAINT DEPT_ID_PK;
ALTER TABLE departments
ENABLE CONSTRAINT DEPT_ID_PK;

ALTER TABLE departments
ENABLE CONSTRAINT DEPT_MGR_FK;

ALTER TABLE departments
ENABLE CONSTRAINT DEPT_LOC_FK;

ALTER TABLE employees
ENABLE CONSTRAINT EMP_DEPT_FK;

ALTER TABLE employees
ENABLE CONSTRAINT EMP_JOB_FK;

ALTER TABLE employees
ENABLE CONSTRAINT EMP_MANAGER_FK;

ALTER TABLE employees
ENABLE CONSTRAINT EMP_EMAIL_UK;

ALTER TABLE employees
ENABLE CONSTRAINT EMP_EMP_ID_PK;